### ISSUE TITLE
It is not possible to change identity on the account settings page

### ISSUE THREAD

**Issue by asbjornu** [piratpartiet/drywall#7]
It fails with a `500 Internal Server Error` and:

```
TypeError: Cannot read property 'User' of undefined
    at EventEmitter.&lt;anonymous&gt; (./views/account/settings/index.js:510:22)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at EventEmitter.&lt;anonymous&gt; (./views/account/settings/index.js:506:14)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at exports.password (./views/account/settings/index.js:536:12)
    at Layer.handle [as handle_request] (./node_modules/express/lib/router/layer.js:95:5)
    at next (./node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (./node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (./node_modules/express/lib/router/layer.js:95:5)
    at ./node_modules/express/lib/router/index.js:277:22
    at Function.process_params (./node_modules/express/lib/router/index.js:330:12)
    at next (./node_modules/express/lib/router/index.js:271:10)
    at next (./node_modules/express/lib/router/route.js:121:14)
    at next (./node_modules/express/lib/router/route.js:125:14)
```

**Comment by tobixen** [comment]
Identity?  Like user name?

**Comment by asbjornu** [comment]
@tobixen Yep.
